#!/usr/bin/env bash
#
# bruce-heartbeat-cleanup.sh
#
# Collapses Bruce's per-cron-tick "no-work-this-run" message spam into a
# single messages/bruce-heartbeat.md file.
#
# Why: Bruce writes a new timestamped message file every time its cron ticks
# and finds no pending collect-request.md. At 20-minute cadence that's ~72
# commits/day of pure noise, bloating git history and cluttering messages/.
#
# What this does:
#   1. Finds all messages/*-bruce-status-no-work-this-run.md
#   2. Extracts the latest timestamp from the filenames
#   3. Deletes them all
#   4. Writes a single messages/bruce-heartbeat.md with latest timestamp
#   5. Stages everything (does NOT commit — caller commits)
#
# This is a one-time cleanup. The durable fix is for Bruce to overwrite a
# single heartbeat file instead of creating new ones — proposed in
# messages/2026-04-XX-XXXX-mini-to-bruce-heartbeat-proposal.md
#
# Usage:
#   ./scripts/bruce-heartbeat-cleanup.sh [repo_root]
#
# Default repo_root: /Users/bruce/.openclaw/workspace/gtmdot-sites

set -euo pipefail

REPO="${1:-/Users/bruce/.openclaw/workspace/gtmdot-sites}"
MSG_DIR="$REPO/messages"

if [ ! -d "$MSG_DIR" ]; then
  echo "error: $MSG_DIR not found" >&2
  exit 2
fi

cd "$REPO"

# Collect all no-work heartbeat messages (top-level only, not in subdirs).
# Using while-read for compatibility with bash 3.2 on macOS.
files=()
while IFS= read -r line; do
  files+=("$line")
done < <(
  find messages -maxdepth 1 -type f \
    -name "*-bruce-status-no-work-this-run.md" \
    | sort
)

count=${#files[@]}
if [ "$count" -eq 0 ]; then
  echo "No heartbeat spam to collapse."
  exit 0
fi

latest="${files[$((count-1))]}"
latest_name=$(basename "$latest")
# Filename format: YYYY-MM-DD-HHMM-bruce-status-no-work-this-run.md
# Also tolerate the older YYYYMMDD-HHMM- format we saw once.
last_seen=$(echo "$latest_name" \
  | sed -E 's/-bruce-status-no-work-this-run\.md$//')

# Write the single heartbeat file
cat > "$MSG_DIR/bruce-heartbeat.md" <<EOF
---
from: bruce
to: mini
subject: heartbeat
priority: low
updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
last_no_work: $last_seen
collapsed_count: $count
---

# Bruce heartbeat

Replaces the pattern of committing a new timestamped message per cron tick
when Bruce has no work to do. See:
  - Mini finding #13 (heartbeat commit-bombing the repo)
  - messages/\*-mini-to-bruce-heartbeat-proposal.md

Most recent no-work run: \`$last_seen\`

When Bruce's next cron finds no pending \`collect-request.md\`, it should
overwrite this file (not create a new one). When Bruce DOES find work,
it writes a new \`*-bruce-*-collected.md\` per the normal convention.

This file was generated by \`scripts/bruce-heartbeat-cleanup.sh\` collapsing
$count prior no-work messages.
EOF

# Remove all the old no-work files
for f in "${files[@]}"; do
  git rm --quiet "$f" 2>/dev/null || rm "$f"
done

git add "$MSG_DIR/bruce-heartbeat.md"

echo "Collapsed $count no-work heartbeat messages into messages/bruce-heartbeat.md"
echo "Latest pre-collapse timestamp: $last_seen"
echo
echo "Next: git commit -m 'chore(bruce): collapse per-tick heartbeats into single file'"
