#!/usr/bin/env bash
#
# state-snapshot.sh — populate PIPELINE.md §4 with current pipeline state
#
# Queries Supabase + scans filesystem to produce a snapshot block, then
# rewrites the §4 section of PIPELINE.md in place (between the marker lines).
#
# Usage:
#   ./scripts/state-snapshot.sh           # update PIPELINE.md §4 in place
#   ./scripts/state-snapshot.sh --dry-run # print what would be written, don't modify
#
# Safe to run repeatedly. Idempotent.
#
# Designed to be callable from:
#   - git post-commit hook
#   - `gtmdot-morning-summary` scheduled task
#   - manual invocation

set -euo pipefail

REPO="/Users/bruce/.openclaw/workspace/gtmdot-sites"
PIPELINE_MD="$REPO/PIPELINE.md"
ENV_FILE="$HOME/.openclaw/.env"

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "error: $ENV_FILE not found" >&2
  exit 2
fi

# shellcheck source=/dev/null
set -a
source "$ENV_FILE"
set +a

SUPABASE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-${SUPABASE_SERVICE_KEY:-}}"
SUPABASE_URL="${SUPABASE_URL:-https://qztjoshdrxionhxeieik.supabase.co}"

if [ -z "$SUPABASE_KEY" ]; then
  echo "error: missing SUPABASE_SERVICE_ROLE_KEY / SUPABASE_SERVICE_KEY" >&2
  exit 2
fi

curl_get() {
  curl -s -G \
    -H "apikey: $SUPABASE_KEY" \
    -H "Authorization: Bearer $SUPABASE_KEY" \
    "$@"
}

now="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# ───── stage counts ─────
stage_counts=$(
  curl_get "$SUPABASE_URL/rest/v1/prospects" \
    --data-urlencode "select=stage" \
    --data-urlencode "disqualified=eq.false" \
  | python3 -c "
import json, sys
from collections import Counter
rows = json.load(sys.stdin)
c = Counter(r['stage'] for r in rows if r.get('stage'))
for stage, count in sorted(c.items(), key=lambda x: -x[1]):
    print(f'- {stage}: {count}')
"
)

dead_count=$(
  curl_get "$SUPABASE_URL/rest/v1/prospects" \
    --data-urlencode "select=id" \
    --data-urlencode "disqualified=eq.true" \
    -H "Prefer: count=exact" \
    -o /dev/null -D - | grep -i "content-range" | awk -F'/' '{print $2}' | tr -d '\r\n'
)

# ───── open feedback flags ─────
flag_counts=$(
  curl_get "$SUPABASE_URL/rest/v1/notes" \
    --data-urlencode "select=feedback_status" \
    --data-urlencode "note_type=eq.design_feedback" \
    --data-urlencode "feedback_status=in.(open,in_progress)" \
  | python3 -c "
import json, sys
from collections import Counter
rows = json.load(sys.stdin)
c = Counter(r['feedback_status'] for r in rows if r.get('feedback_status'))
for status, count in c.items():
    print(f'- {status}: {count}')
if not c:
    print('- none')
"
)

# ───── filesystem state ─────
collect_requests=$(find "$REPO/sites" -maxdepth 2 -name "collect-request.md" 2>/dev/null | wc -l | tr -d ' ')
bruce_pending=$(find "$REPO/sites" -maxdepth 2 -name "bruce-collected.md" -mtime -2 2>/dev/null | wc -l | tr -d ' ')
needs_repolish=$(find "$REPO/sites" -maxdepth 2 -name "needs-repolish.md" 2>/dev/null | wc -l | tr -d ' ')

# ───── gbp_snapshot staleness ─────
gbp_stats=$(
  python3 <<PYEOF
import json, os
from pathlib import Path
from datetime import datetime, timezone, timedelta

sites = Path("$REPO/sites")
now = datetime.now(timezone.utc)
fresh = stale_soft = stale_hard = total = 0
for d in sites.iterdir():
    if not d.is_dir(): continue
    p = d / "gbp_snapshot.json"
    if not p.exists(): continue
    try:
        snap = json.loads(p.read_text())
    except Exception:
        continue
    total += 1
    fetched = snap.get("fetched_at", "")
    if fetched.endswith("Z"):
        fetched = fetched[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(fetched)
    except Exception:
        continue
    age = now - dt
    policy = snap.get("staleness_policy", {})
    soft_d = policy.get("soft_stale_days", 14)
    hard_d = policy.get("hard_stale_days", 30)
    if age >= timedelta(days=hard_d):
        stale_hard += 1
    elif age >= timedelta(days=soft_d):
        stale_soft += 1
    else:
        fresh += 1
print(f"- total: {total}")
print(f"- fresh (<14d): {fresh}")
print(f"- soft-stale (14-30d): {stale_soft}")
print(f"- hard-stale (>30d): {stale_hard}")
PYEOF
)

# ───── compose the block ─────
block=$(cat <<EOF
<!-- state-snapshot:begin — auto-generated by scripts/state-snapshot.sh; do not edit by hand -->
*Last updated: $now*

**Prospect stages (non-disqualified):**
$stage_counts

**Disqualified:** $dead_count

**Open design-feedback flags:**
$flag_counts

**Enrichment loop state:**
- in-flight collect-requests: $collect_requests
- fresh bruce-collected (<48h): $bruce_pending
- needs-repolish signals waiting R1VS: $needs_repolish

**GBP snapshot staleness:**
$gbp_stats

<!-- state-snapshot:end -->
EOF
)

if [ "$DRY_RUN" -eq 1 ]; then
  echo "$block"
  exit 0
fi

# ───── splice into PIPELINE.md between §4 markers ─────
if [ ! -f "$PIPELINE_MD" ]; then
  echo "error: $PIPELINE_MD not found" >&2
  exit 2
fi

# Ensure markers exist; if not, insert a default block under §4 heading
if ! grep -q "state-snapshot:begin" "$PIPELINE_MD"; then
  # Find §4 header and append empty markers just below it
  python3 <<PYEOF
from pathlib import Path
p = Path("$PIPELINE_MD")
text = p.read_text()
needle = "## §4 Current State Snapshot"
if needle in text:
    idx = text.index(needle)
    # Find end of the section header line
    nl = text.index("\n", idx) + 1
    insertion = ("\n<!-- state-snapshot:begin -->\n"
                 "(populated by scripts/state-snapshot.sh)\n"
                 "<!-- state-snapshot:end -->\n\n")
    # Only insert if the user's initial "*Placeholder*" text is present
    if "*Placeholder" in text[nl:nl+300]:
        # Replace the whole preamble until next "##" with our insertion
        nxt = text.index("\n## ", nl)
        text = text[:nl] + insertion + text[nxt+1:]
    else:
        text = text[:nl] + insertion + text[nl:]
    p.write_text(text)
PYEOF
fi

# Splice the new block in place of whatever's between the markers
python3 <<PYEOF
from pathlib import Path
import re
p = Path("$PIPELINE_MD")
text = p.read_text()
pattern = re.compile(
    r"<!-- state-snapshot:begin[^>]*-->.*?<!-- state-snapshot:end -->",
    re.DOTALL,
)
new_block = """$block"""
text = pattern.sub(new_block, text, count=1)
p.write_text(text)
print("updated $PIPELINE_MD")
PYEOF
